import { ChangeEvent, DragEvent, useRef, useState } from "react";
import { BarChart3, CalendarDays, Check, FileText, ImagePlus, LayoutDashboard, LogOut, Save, Ticket, Upload, Users } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { events, formatEventDate, formatPrice, ticketsLeft } from "@/lib/events";

const logo = "https://cdn.builder.io/api/v1/image/assets%2F4f039897198345dd9424e863acd695f%2Fbc7ec222814d44c8bb5bc1028c0274bc?format=webp&width=800&height=1200";
type Tab = "Overview" | "Current event" | "Future event" | "Tickets" | "Attendees" | "Analytics";

export default function AdminGate() {
  const [authenticated, setAuthenticated] = useState(() => localStorage.getItem("hili-admin-auth") === "true");
  if (!authenticated) return <AdminLogin onLogin={() => { localStorage.setItem("hili-admin-auth", "true"); setAuthenticated(true); }} />;
  return <AdminDashboard onLogout={() => { localStorage.removeItem("hili-admin-auth"); setAuthenticated(false); }} />;
}

function AdminLogin({ onLogin }: { onLogin: () => void }) {
  const [email, setEmail] = useState(""); const [password, setPassword] = useState("");
  return <div className="flex min-h-screen items-center justify-center bg-[#0b0b0b] px-5 py-12 text-white"><div className="w-full max-w-md"><div className="flex items-center gap-3"><img src={logo} alt="Hili" className="h-10 w-10 rounded-full object-cover" /><span className="font-display text-xl font-bold">Hili Admin</span></div><div className="mt-12 rounded-3xl bg-white p-6 text-[#0b0b0b] shadow-2xl sm:p-8"><p className="text-[10px] font-semibold uppercase tracking-[.3em] text-black/45">Private workspace</p><h1 className="mt-3 font-display text-3xl font-bold">Welcome back.</h1><p className="mt-2 text-sm text-black/55">Sign in to manage Hili events and ticket sales.</p><form onSubmit={(e) => { e.preventDefault(); if (email && password) onLogin(); }} className="mt-8 space-y-4"><label className="block text-sm font-semibold">Email<Input className="mt-2" type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="you@hili.co.ke" required /></label><label className="block text-sm font-semibold">Password<Input className="mt-2" type="password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="••••••••" required /></label><Button type="submit" className="mt-3 h-12 w-full bg-[#c1e51a] text-black hover:bg-[#b1d410]">Sign in to admin</Button></form></div></div></div>;
}

function AdminDashboard({ onLogout }: { onLogout: () => void }) {
  const [tab, setTab] = useState<Tab>("Overview"); const [saved, setSaved] = useState(false);
  const tabs: { label: Tab; icon: typeof LayoutDashboard }[] = [{ label: "Overview", icon: LayoutDashboard }, { label: "Current event", icon: CalendarDays }, { label: "Future event", icon: ImagePlus }, { label: "Tickets", icon: Ticket }, { label: "Attendees", icon: Users }, { label: "Analytics", icon: BarChart3 }];
  return <div className="min-h-screen bg-[#f4f4ef] text-[#0b0b0b]"><aside className="fixed inset-y-0 left-0 hidden w-64 flex-col border-r border-black/10 bg-[#0b0b0b] p-6 text-white lg:flex"><Brand /><Nav tabs={tabs} active={tab} setActive={setTab} /><div className="mt-auto rounded-2xl bg-white/10 p-4"><p className="text-xs text-white/50">Signed in as</p><p className="mt-1 truncate text-sm font-semibold">Hili Events Team</p><button onClick={onLogout} className="mt-3 flex items-center gap-2 text-xs text-white/55 hover:text-white"><LogOut className="h-3.5 w-3.5" /> Sign out</button></div></aside><main className="lg:pl-64"><header className="border-b border-black/10 bg-[#f4f4ef] px-5 py-5 sm:px-10"><div className="flex items-center justify-between gap-4"><div><p className="text-[10px] uppercase tracking-[.25em] text-black/45">Hili workspace</p><h1 className="mt-1 font-display text-xl font-bold">{tab}</h1></div><Button onClick={() => setSaved(true)} className="bg-[#c1e51a] text-black hover:bg-[#b1d410]"><Save className="h-4 w-4" /><span className="hidden sm:inline">Save changes</span></Button></div><div className="mt-5 overflow-x-auto lg:hidden"><div className="flex min-w-max gap-2 pb-1">{tabs.map(({ label, icon: Icon }) => <button key={label} onClick={() => setTab(label)} className={`flex items-center gap-2 rounded-full px-4 py-2 text-xs font-semibold ${tab === label ? "bg-[#0b0b0b] text-white" : "bg-black/5 text-black/55"}`}><Icon className="h-3.5 w-3.5" />{label}</button>)}</div></div></header><div className="p-5 sm:p-10">{tab === "Overview" && <Overview />} {tab === "Current event" && <CurrentEvent />} {tab === "Future event" && <FutureEvent />} {tab === "Tickets" && <Tickets />} {(tab === "Attendees" || tab === "Analytics") && <EmptyTab tab={tab} />}{saved && <div className="fixed bottom-5 right-5 flex items-center gap-2 rounded-full bg-[#0b0b0b] px-5 py-3 text-sm font-semibold text-white shadow-xl"><Check className="h-4 w-4 text-[#c1e51a]" /> Changes saved</div>}</div></main></div>;
}
function Brand() { return <div className="flex items-center gap-3"><img src={logo} alt="Hili" className="h-9 w-9 rounded-full object-cover" /><span className="font-display text-lg font-bold">Hili Admin</span></div>; }
function Nav({ tabs, active, setActive }: { tabs: { label: Tab; icon: typeof LayoutDashboard }[]; active: Tab; setActive: (tab: Tab) => void }) { return <><p className="mt-14 text-[10px] uppercase tracking-[.25em] text-white/40">Workspace</p><nav className="mt-4 space-y-1">{tabs.map(({ label, icon: Icon }) => <button key={label} onClick={() => setActive(label)} className={`flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-sm ${active === label ? "bg-[#c1ff1a] font-semibold text-black" : "text-white/60 hover:bg-white/10 hover:text-white"}`}><Icon className="h-4 w-4" /> {label}</button>)}</nav></>; }
function Overview() { return <div><p className="text-sm font-semibold text-black/50">Good morning, Hili</p><h2 className="mt-2 font-display text-3xl font-bold tracking-tight sm:text-4xl">Your events at a glance.</h2><div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Revenue", "KSh 684,500"], ["Tickets sold", "342"], ["Upcoming events", "1"], ["Check-ins today", "0"]].map(([label, value]) => <div key={label} className="rounded-2xl border border-black/10 bg-white p-5"><p className="text-sm text-black/50">{label}</p><p className="mt-3 font-display text-2xl font-bold sm:text-3xl">{value}</p></div>)}</div><div className="mt-8 rounded-3xl border border-black/10 bg-white p-6"><p className="text-xs uppercase tracking-widest text-black/45">Current event</p><h3 className="mt-3 font-display text-2xl font-bold">{events[0].title}</h3><p className="mt-2 text-sm text-black/55">{formatEventDate(events[0].date)} · {events[0].venue}</p><div className="mt-6 h-3 overflow-hidden rounded-full bg-black/10"><div className="h-full w-[48%] rounded-full bg-[#a6c900]" /></div><p className="mt-2 text-xs text-black/50">342 of 700 tickets sold</p></div></div>; }
function CurrentEvent() { const [event, setEvent] = useState({ ...events[0] }); const [poster, setPoster] = useState(event.coverImage); const fileRef = useRef<HTMLInputElement>(null); const set = (key: "title" | "venue" | "date" | "city", value: string) => setEvent((current) => ({ ...current, [key]: value })); const upload = (file?: File) => { if (!file?.type.startsWith("image/")) return; const reader = new FileReader(); reader.onload = () => setPoster(String(reader.result)); reader.readAsDataURL(file); }; const drop = (e: DragEvent<HTMLDivElement>) => { e.preventDefault(); upload(e.dataTransfer.files[0]); }; return <div className="max-w-5xl"><p className="text-sm text-black/50">Update the event customers currently see</p><h2 className="mt-2 font-display text-3xl font-bold">Current event</h2><div className="mt-8 grid gap-6 lg:grid-cols-[.8fr_1.2fr]"><div><label className="text-sm font-semibold">Poster</label><div onClick={() => fileRef.current?.click()} onDragOver={(e) => e.preventDefault()} onDrop={drop} className="mt-3 cursor-pointer overflow-hidden rounded-3xl border-2 border-dashed border-black/20 bg-white"><img src={poster} alt="Poster" className="aspect-[4/3] w-full object-cover" /><div className="flex items-center justify-center gap-2 p-4 text-sm font-semibold"><Upload className="h-4 w-4" /> Choose or drop image</div></div><input ref={fileRef} onChange={(e: ChangeEvent<HTMLInputElement>) => upload(e.target.files?.[0])} type="file" accept="image/*" className="hidden" /></div><div className="rounded-3xl border border-black/10 bg-white p-6"><Field label="Event name" value={event.title} onChange={(v) => set("title", v)} /><Field label="Venue" value={event.venue} onChange={(v) => set("venue", v)} /><div className="grid gap-4 sm:grid-cols-2"><Field label="Date" value={event.date} onChange={(v) => set("date", v)} /><Field label="City" value={event.city} onChange={(v) => set("city", v)} /></div><label className="mt-5 block text-sm font-semibold">Description<Textarea className="mt-2 min-h-28" defaultValue={event.description} /></label></div></div><TicketEditor /></div>; }
function Field({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="mb-5 block text-sm font-semibold">{label}<Input className="mt-2" value={value} onChange={(e) => onChange(e.target.value)} /></label>; }
function TicketEditor() { const [tiers, setTiers] = useState(events[0].ticketTypes); return <section className="mt-10"><div className="flex items-end justify-between"><div><p className="text-sm text-black/50">Pricing and availability</p><h3 className="mt-1 font-display text-2xl font-bold">Ticket tiers</h3></div><Button variant="outline" size="sm" onClick={() => setTiers([...tiers, { id: `new-${tiers.length}`, name: "New tier", description: "", price: 0, quantityTotal: 100, quantitySold: 0, maxPerOrder: 6 }])}>Add tier</Button></div><div className="mt-5 grid gap-4">{tiers.map((tier, index) => <div key={tier.id} className="rounded-2xl border border-black/10 bg-white p-5"><div className="grid gap-4 sm:grid-cols-3"><Field label="Tier name" value={tier.name} onChange={(value) => setTiers(tiers.map((item, i) => i === index ? { ...item, name: value } : item))} /><Field label="Price (KSh)" value={String(tier.price)} onChange={(value) => setTiers(tiers.map((item, i) => i === index ? { ...item, price: Number(value) || 0 } : item))} /><Field label="Quantity" value={String(tier.quantityTotal)} onChange={(value) => setTiers(tiers.map((item, i) => i === index ? { ...item, quantityTotal: Number(value) || 0 } : item))} /></div><div className="grid gap-4 sm:grid-cols-2"><Field label="Card description" value={tier.description} onChange={(value) => setTiers(tiers.map((item, i) => i === index ? { ...item, description: value } : item))} /><p className="pt-1 text-sm text-black/55">{ticketsLeft(tier)} remaining · {tier.quantitySold} sold · max {tier.maxPerOrder} per order</p></div></div>)}</div></section>; }
function FutureEvent() { const [poster, setPoster] = useState(""); const fileRef = useRef<HTMLInputElement>(null); const upload = (file?: File) => { if (!file?.type.startsWith("image/")) return; const reader = new FileReader(); reader.onload = () => setPoster(String(reader.result)); reader.readAsDataURL(file); }; return <div className="max-w-3xl"><p className="text-sm text-black/50">Prepare what is coming next</p><h2 className="mt-2 font-display text-3xl font-bold">Future event</h2><p className="mt-3 max-w-lg text-sm text-black/55">Add a poster and a few details now. You can fill in ticketing and publish later.</p><div className="mt-8 grid gap-6 rounded-3xl border border-black/10 bg-white p-6 sm:grid-cols-2"><div onClick={() => fileRef.current?.click()} onDragOver={(e) => e.preventDefault()} onDrop={(e) => { e.preventDefault(); upload(e.dataTransfer.files[0]); }} className="cursor-pointer overflow-hidden rounded-2xl border-2 border-dashed border-black/15 bg-[#f4f4ef] text-center"><div className="flex aspect-[4/3] items-center justify-center">{poster ? <img src={poster} alt="Future event poster" className="h-full w-full object-cover" /> : <ImagePlus className="h-10 w-10 text-black/30" />}</div><p className="p-3 text-sm font-semibold">Upload poster</p></div><input ref={fileRef} onChange={(e) => upload(e.target.files?.[0])} type="file" accept="image/*" className="hidden" /><div><Field label="Event name" value="" onChange={() => undefined} /><Field label="Expected date" value="" onChange={() => undefined} /><label className="text-sm font-semibold">Short note<Textarea className="mt-2 min-h-24" placeholder="A few words about the event" /></label></div></div></div>; }
function Tickets() { return <div className="max-w-5xl"><p className="text-sm text-black/50">Issued tickets</p><h2 className="mt-2 font-display text-3xl font-bold">View tickets</h2><div className="mt-8 grid gap-4 sm:grid-cols-2">{["HILI-8K2P-01", "HILI-7R4M-02", "HILI-3Q9A-03", "HILI-1Z8F-04"].map((id, i) => <div key={id} className="relative overflow-hidden rounded-2xl border border-black/10 bg-white p-5"><div className="flex items-center justify-between"><span className="rounded-full bg-[#c1e51a] px-2.5 py-1 text-[10px] font-bold">VALID</span><Ticket className="h-5 w-5 text-black/25" /></div><p className="mt-5 text-xs text-black/45">Ticket number</p><p className="mt-1 font-mono text-sm font-bold">{id}</p><div className="mt-4 grid grid-cols-2 gap-3 border-t border-dashed border-black/15 pt-4 text-sm"><div><p className="text-xs text-black/45">Attendee</p><p className="font-semibold">{["John Doe", "Amina W.", "Kevin M.", "Sarah K."][i]}</p></div><div><p className="text-xs text-black/45">Type</p><p className="font-semibold">{i === 1 ? "VIP" : "Regular"}</p></div></div></div>)}</div></div>; }
function EmptyTab({ tab }: { tab: Tab }) { return <div className="rounded-3xl border border-black/10 bg-white p-7"><FileText className="h-7 w-7" /><h2 className="mt-5 font-display text-2xl font-bold">{tab}</h2><p className="mt-2 max-w-md text-sm leading-6 text-black/55">The workspace is ready for {tab.toLowerCase()} management. Connect the Supabase data layer to make these records live.</p></div>; }
