import { ChangeEvent, DragEvent, Dispatch, RefObject, SetStateAction, useEffect, useRef, useState } from "react";
import { BarChart3, CalendarDays, Check, ImagePlus, LayoutDashboard, Save, Ticket, Upload, Users } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { events } from "@/lib/events";

export default function AdminPage() {
  const [event, setEvent] = useState(() => {
    const stored = localStorage.getItem("hili-admin-event");
    return stored ? { ...events[0], ...JSON.parse(stored) } : { ...events[0] };
  });
  const [active, setActive] = useState("Event details");
  const [saved, setSaved] = useState(false);
  const [poster, setPoster] = useState(() => localStorage.getItem("hili-admin-poster") || events[0].coverImage);
  useEffect(() => { localStorage.setItem("hili-admin-event", JSON.stringify(event)); localStorage.setItem("hili-admin-poster", poster); }, [event, poster]);
  const fileRef = useRef<HTMLInputElement>(null);
  const update = (key: "title" | "venue" | "date" | "city", value: string) => { setEvent((current) => ({ ...current, [key]: value })); setSaved(false); };
  const upload = (file?: File) => { if (!file || !file.type.startsWith("image/")) return; const reader = new FileReader(); reader.onload = () => { setPoster(String(reader.result)); setSaved(false); }; reader.readAsDataURL(file); };
  const onDrop = (e: DragEvent<HTMLDivElement>) => { e.preventDefault(); upload(e.dataTransfer.files[0]); };
  const onFile = (e: ChangeEvent<HTMLInputElement>) => upload(e.target.files?.[0]);
  const nav = [{ label: "Overview", icon: LayoutDashboard }, { label: "Event details", icon: CalendarDays }, { label: "Tickets", icon: Ticket }, { label: "Attendees", icon: Users }, { label: "Analytics", icon: BarChart3 }];
  return <div className="min-h-screen bg-[#f4f4ef] text-[#0b0b0b]"><aside className="fixed inset-y-0 left-0 hidden w-64 flex-col border-r border-black/10 bg-[#0b0b0b] p-6 text-white lg:flex"><div className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center overflow-hidden rounded-full bg-[#c1ff1a]"><img src="https://cdn.builder.io/api/v1/image/assets%2F4f039897198345dd9424e863acd695f%2Fbc7ec222814d44c8bb5bc1028c0274bc?format=webp&width=800&height=1200" alt="Hili" className="h-full w-full object-cover" /></span><span className="font-display text-lg font-bold">Hili Admin</span></div><p className="mt-14 text-[10px] uppercase tracking-[.25em] text-white/40">Workspace</p><nav className="mt-4 space-y-1">{nav.map(({ label, icon: Icon }) => <button key={label} type="button" onClick={() => setActive(label)} className={`flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-sm ${active === label ? "bg-[#c1ff1a] font-semibold text-black" : "text-white/60 hover:bg-white/10 hover:text-white"}`}><Icon className="h-4 w-4" /> {label}</button>)}</nav><div className="mt-auto rounded-2xl bg-white/10 p-4"><p className="text-xs text-white/50">Signed in as</p><p className="mt-1 text-sm font-semibold">Hili Events Team</p></div></aside><main className="lg:pl-64"><header className="flex h-20 items-center justify-between border-b border-black/10 bg-[#f4f4ef] px-5 sm:px-10"><div><p className="text-[10px] uppercase tracking-[.25em] text-black/45">Hili workspace</p><h1 className="mt-1 font-display text-xl font-bold">{active}</h1></div><div className="flex items-center gap-3"><span className="hidden text-sm text-black/50 sm:block">All changes are saved locally</span><Button onClick={() => setSaved(true)} className="bg-[#c1ff1a] text-black hover:bg-[#b2ed12]"><Save className="h-4 w-4" /> Save changes</Button></div></header><div className="p-5 sm:p-10">{active === "Overview" ? <Overview event={event} /> : active === "Event details" ? <Details event={event} poster={poster} update={update} upload={upload} onDrop={onDrop} fileRef={fileRef} onFile={onFile} /> : active === "Tickets" ? <Tickets event={event} setEvent={setEvent} /> : <div className="rounded-3xl border border-black/10 bg-white p-8"><h2 className="font-display text-2xl font-bold">{active}</h2><p className="mt-3 max-w-md text-black/55">This workspace is ready for {active.toLowerCase()} management. Connect your Supabase data to make these controls live.</p></div>}{saved && <div className="fixed bottom-6 right-6 flex items-center gap-2 rounded-full bg-[#0b0b0b] px-5 py-3 text-sm font-semibold text-white shadow-xl"><Check className="h-4 w-4 text-[#c1ff1a]" /> Changes saved</div>}</div></main></div>;
}
function Overview({ event }: { event: typeof events[0] }) { return <div><div className="mb-8 flex items-end justify-between"><div><p className="text-sm font-semibold text-black/50">Good morning, Hili</p><h2 className="mt-2 font-display text-4xl font-bold tracking-tight">Your events at a glance.</h2></div><span className="rounded-full bg-[#c1ff1a] px-3 py-1 text-xs font-bold">Live workspace</span></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Revenue", "KSh 684,500"], ["Tickets sold", "342"], ["Upcoming events", "1"], ["Check-ins today", "0"]].map(([label, value]) => <div key={label} className="rounded-2xl border border-black/10 bg-white p-5"><p className="text-sm text-black/50">{label}</p><p className="mt-3 font-display text-3xl font-bold">{value}</p></div>)}</div><div className="mt-8 grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><div className="rounded-3xl border border-black/10 bg-white p-6"><p className="text-xs uppercase tracking-widest text-black/45">Upcoming event</p><div className="mt-5 flex gap-5"><img src={event.coverImage} alt={event.title} className="h-28 w-24 rounded-xl object-cover" /><div><h3 className="font-display text-xl font-bold">{event.title}</h3><p className="mt-2 text-sm text-black/55">{event.date} · {event.venue}</p><p className="mt-5 text-sm font-semibold text-[#748f00]">342 attendees registered</p></div></div></div><div className="rounded-3xl bg-[#c1ff1a] p-6"><ImagePlus className="h-7 w-7" /><h3 className="mt-12 font-display text-2xl font-bold">Make it yours.</h3><p className="mt-2 text-sm text-black/60">Update your poster, tiers, and event details from the sidebar.</p></div></div></div>; }
function Details({ event, poster, update, upload, onDrop, fileRef, onFile }: { event: typeof events[0]; poster: string; update: (key: string, value: string) => void; upload: (file?: File) => void; onDrop: (e: DragEvent<HTMLDivElement>) => void; fileRef: RefObject<HTMLInputElement>; onFile: (e: ChangeEvent<HTMLInputElement>) => void }) { return <div className="max-w-5xl"><p className="text-sm text-black/50">Edit your upcoming experience</p><h2 className="mt-2 font-display text-3xl font-bold">Event details</h2><div className="mt-8 grid gap-6 lg:grid-cols-[1fr_1.2fr]"><div><label className="text-sm font-semibold">Event poster</label><div onDragOver={(e) => e.preventDefault()} onDrop={onDrop} onClick={() => fileRef.current?.click()} className="mt-3 cursor-pointer overflow-hidden rounded-3xl border-2 border-dashed border-black/20 bg-white hover:border-black/50"><img src={poster} alt="Event poster preview" className="aspect-[4/3] w-full object-cover" /><div className="flex items-center justify-center gap-2 p-4 text-sm font-semibold"><Upload className="h-4 w-4" /> Drop image here or choose a file</div></div><input ref={fileRef} onChange={onFile} type="file" accept="image/*" className="hidden" /><p className="mt-2 text-xs text-black/45">PNG, JPG, or WEBP. Uploads are previewed locally before saving.</p></div><div className="rounded-3xl border border-black/10 bg-white p-6"><Field label="Event name" value={event.title} onChange={(v) => update("title", v)} /><Field label="Venue" value={event.venue} onChange={(v) => update("venue", v)} /><div className="grid gap-4 sm:grid-cols-2"><Field label="Date" value={event.date} onChange={(v) => update("date", v)} /><Field label="City" value={event.city} onChange={(v) => update("city", v)} /></div><label className="mt-5 block text-sm font-semibold">Description</label><Textarea className="mt-2 min-h-28" value={event.description} onChange={(e) => update("description", e.target.value)} /></div></div></div>; }
function Field({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="mb-5 block text-sm font-semibold">{label}<Input className="mt-2" value={value} onChange={(e) => onChange(e.target.value)} /></label>; }
function Tickets({ event, setEvent }: { event: typeof events[0]; setEvent: Dispatch<SetStateAction<typeof events[0]>> }) { return <div className="max-w-4xl"><p className="text-sm text-black/50">Manage pricing and availability</p><h2 className="mt-2 font-display text-3xl font-bold">Ticket types</h2><div className="mt-8 space-y-4">{event.ticketTypes.map((ticket, index) => <div key={ticket.id} className="grid gap-4 rounded-2xl border border-black/10 bg-white p-5 md:grid-cols-[1fr_130px_130px]"><Field label="Tier name" value={ticket.name} onChange={(value) => setEvent((current) => ({ ...current, ticketTypes: current.ticketTypes.map((item, i) => i === index ? { ...item, name: value } : item) }))} /><Field label="Price (KSh)" value={String(ticket.price)} onChange={(value) => setEvent((current) => ({ ...current, ticketTypes: current.ticketTypes.map((item, i) => i === index ? { ...item, price: Number(value) || 0 } : item) }))} /><Field label="Quantity" value={String(ticket.quantityTotal)} onChange={(value) => setEvent((current) => ({ ...current, ticketTypes: current.ticketTypes.map((item, i) => i === index ? { ...item, quantityTotal: Number(value) || 0 } : item) }))} /></div>)}</div><Button variant="outline" className="mt-5" onClick={() => setEvent((current) => ({ ...current, ticketTypes: [...current.ticketTypes, { id: `t${current.ticketTypes.length + 1}`, name: "New tier", description: "", price: 0, quantityTotal: 100, quantitySold: 0, maxPerOrder: 6 }] }))}>Add ticket tier</Button></div>; }
