import { useMemo, useState } from "react";
import { Link, useSearchParams, useParams } from "react-router-dom";
import { ArrowLeft, ArrowRight, Minus, Plus } from "lucide-react";
import Layout from "@/components/layout/Layout";
import PlaceholderPage from "@/components/PlaceholderPage";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { events, formatPrice, getEventBySlug } from "@/lib/events";

export default function AttendeePage() {
  const { slug } = useParams(); const [params] = useSearchParams(); const event = getEventBySlug(slug || events[0].slug); const ticket = event?.ticketTypes.find((item) => item.id === params.get("ticket")) || event?.ticketTypes[0]; const [quantity, setQuantity] = useState(1); const [names, setNames] = useState([""]);
  const total = (ticket?.price || 0) * quantity;
  const updateQuantity = (next: number) => { const value = Math.max(1, Math.min(ticket?.maxPerOrder || 6, next)); setQuantity(value); setNames((current) => Array.from({ length: value }, (_, i) => current[i] || "")); };
  const canContinue = useMemo(() => names.every(Boolean), [names]);
  if (!event || !ticket) return <PlaceholderPage title="Ticket unavailable" description="Please return to the event and choose another ticket." />;
  return <Layout><div className="container max-w-3xl py-12 md:py-20"><Link to={`/tickets/${event.slug}`} className="inline-flex items-center gap-2 text-sm text-muted-foreground"><ArrowLeft className="h-4 w-4" /> Back to tickets</Link><p className="mt-10 text-[10px] font-semibold uppercase tracking-[.3em] text-primary">Step 2 / Attendees</p><div className="mt-3 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h1 className="font-display text-4xl font-bold tracking-tight">Who is coming?</h1><p className="mt-2 text-muted-foreground">{ticket.name} · {formatPrice(ticket.price)} each</p></div><div className="flex items-center gap-3 rounded-full border border-border px-3 py-2"><button type="button" onClick={() => updateQuantity(quantity - 1)} className="rounded-full p-1 hover:bg-muted"><Minus className="h-4 w-4" /></button><span className="min-w-5 text-center font-semibold">{quantity}</span><button type="button" onClick={() => updateQuantity(quantity + 1)} className="rounded-full p-1 hover:bg-muted"><Plus className="h-4 w-4" /></button></div></div><div className="mt-8 space-y-3">{names.map((name, index) => <div key={index} className="rounded-2xl border border-border bg-card p-5"><label className="text-sm font-semibold">Ticket holder {index + 1}</label><Input className="mt-3" placeholder="Full name" value={name} onChange={(e) => setNames((current) => current.map((item, i) => i === index ? e.target.value : item))} /></div>)}</div><div className="mt-8 rounded-2xl bg-muted/60 p-5"><h2 className="font-display font-semibold">Purchaser details</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><Input placeholder="Email address" type="email" /><Input placeholder="Phone number" type="tel" /></div><p className="mt-3 text-xs text-muted-foreground">Your tickets will be sent to this email after payment.</p></div><div className="mt-8 flex items-center justify-between border-t border-border pt-6"><div><p className="text-sm text-muted-foreground">Total</p><p className="font-display text-2xl font-bold">{formatPrice(total)}</p></div><Button asChild size="lg" disabled={!canContinue}><Link to={`/checkout/${event.slug}?ticket=${ticket.id}&quantity=${quantity}`}>Continue to checkout <ArrowRight className="h-4 w-4" /></Link></Button></div></div></Layout>;
}
