import { Link } from "react-router-dom";
import { ArrowRight, CalendarDays, MapPin } from "lucide-react";
import Layout from "@/components/layout/Layout";
import { Button } from "@/components/ui/button";
import { events, formatEventDate } from "@/lib/events";

const upcomingPoster = "https://cdn.builder.io/api/v1/image/assets%2F4f039897198345dd9424e863acd695f%2F68999b7a557b4c4eb6f5334dea8b59aa?format=webp&width=800&height=1200";
const upcoming = events[0];
const future = events[1];

export default function Index() {
  return <Layout><section className="bg-[#d8f54a] text-[#0b0b0b]"><div className="container grid min-h-[calc(100vh-4rem)] items-center gap-12 py-14 lg:grid-cols-[.9fr_1.1fr] lg:py-20"><div className="max-w-xl"><p className="text-[10px] font-semibold uppercase tracking-[.3em]">Hili presents</p><h1 className="mt-6 font-display text-5xl font-bold leading-[.92] tracking-[-.07em] sm:text-7xl md:text-8xl">{upcoming.title}</h1><p className="mt-7 max-w-sm text-base leading-7 text-black/65">{upcoming.shortDescription} Come through for a day made for music, movement, and your favourite people.</p><Button asChild size="lg" variant="secondary" className="mt-8"><Link to={`/events/${upcoming.slug}`}>View event details <ArrowRight className="h-4 w-4" /></Link></Button></div><div className="relative mx-auto w-full max-w-[500px]"><div className="overflow-hidden rounded-[2rem] bg-[#171717] shadow-2xl"><img src={upcomingPoster} alt={`${upcoming.title} poster`} onError={(e) => { e.currentTarget.src = upcoming.coverImage; }} className="aspect-[4/5] w-full object-cover" /></div><div className="absolute -bottom-5 -right-4 rounded-2xl bg-[#f4f1ea] px-5 py-4 shadow-xl sm:-right-7"><p className="text-[10px] font-semibold uppercase tracking-widest text-black/45">Event date</p><p className="mt-1 font-display text-sm font-bold">{formatEventDate(upcoming.date)}</p></div></div></div></section><section className="bg-[#f4f1ea]"><div className="container grid gap-12 py-20 md:grid-cols-[.85fr_1.15fr] md:py-28"><div><p className="text-[10px] font-semibold uppercase tracking-[.3em] text-black/45">What comes next</p><h2 className="mt-5 max-w-md font-display text-4xl font-bold leading-tight tracking-tight sm:text-5xl">Keep your calendar open.</h2></div><div><div className="grid gap-6 border-y border-black/15 py-7 sm:grid-cols-3"><Detail icon={CalendarDays} label="Proposed date" value={formatEventDate(future.date)} /><Detail icon={MapPin} label="City" value={future.city} /><Detail label="Status" value="Coming soon" /></div><p className="mt-7 max-w-lg text-sm leading-7 text-black/55">{future.shortDescription} We are putting the final touches together. Follow Hili for the announcement and first access.</p><Link to="/future" className="mt-7 inline-flex items-center gap-2 text-sm font-bold underline decoration-[#859900] decoration-2 underline-offset-4">Explore the next one <ArrowRight className="h-4 w-4" /></Link></div></div></section></Layout>;
}
function Detail({ icon: Icon, label, value }: { icon?: typeof CalendarDays; label: string; value: string }) { return <div className="flex gap-3">{Icon && <Icon className="mt-0.5 h-4 w-4 shrink-0 text-[#657600]" />}<div><p className="text-[10px] font-semibold uppercase tracking-widest text-black/45">{label}</p><p className="mt-1 text-sm font-semibold">{value}</p></div></div>; }
