import type { ReactNode } from "react";
import Layout from "@/components/layout/Layout";

export function TermsPage() {
  return <Legal title="Terms & conditions" eyebrow="Good to know"><p>These terms describe how Hili events and ticket purchases work. By purchasing a ticket, you agree to follow the event policies shown on the event page.</p><h2>Tickets and payment</h2><p>Tickets are issued after successful payment confirmation. Ticket availability, pricing, and closing dates are controlled by Hili and may change before an event sells out.</p><h2>Event access</h2><p>Bring your digital ticket and a valid form of identification where required. Hili reserves the right to refuse entry when event policies are not followed.</p><h2>Contact</h2><p>For questions about a payment or ticket, email hello@hili.co.ke with your order details.</p></Legal>;
}
export function PrivacyPage() {
  return <Legal title="Privacy policy" eyebrow="Your privacy matters"><p>Hili collects the information needed to process ticket purchases and help you attend our events.</p><h2>Information we collect</h2><p>When you purchase a ticket, we collect attendee names and the purchaser's email address and phone number. Payment processing is handled through secure payment providers.</p><h2>How we use it</h2><p>We use this information to issue tickets, send event updates, verify entry, and provide support. We do not sell your personal information.</p><h2>Questions</h2><p>Contact hello@hili.co.ke if you have questions about your information or your ticket.</p></Legal>;
}
function Legal({ title, eyebrow, children }: { title: string; eyebrow: string; children: ReactNode }) { return <Layout><article className="container max-w-2xl py-16 md:py-24"><p className="text-[10px] font-semibold uppercase tracking-[.3em] text-primary">{eyebrow}</p><h1 className="mt-4 font-display text-4xl font-bold tracking-tight md:text-5xl">{title}</h1><div className="mt-10 space-y-5 text-base leading-8 text-muted-foreground [&_h2]:mt-10 [&_h2]:font-display [&_h2]:text-xl [&_h2]:font-bold [&_h2]:text-foreground">{children}</div></article></Layout>; }
